In [1]:
import torch
model = torch.load('pretrain_model/IP-Adapter/sdxl_models/ip-adapter_sdxl.bin',map_location='cpu')

In [4]:
model['image_proj']['proj.weight'].shape

torch.Size([8192, 1280])

In [1]:
import torch
model = torch.load('checkpoints/sd15_latent_new_lr_1e-5_4a100-motion-noupdate-1022-with-ref-noisy-cross-attn/checkpoint-40000/pytorch_model.bin',map_location='cpu')

In [2]:
for key in model.keys():
    print(key)

down_blocks.0.motion_modules.0.transformer_blocks.0.pos_embed.pe
down_blocks.0.motion_modules.1.transformer_blocks.0.pos_embed.pe
down_blocks.1.motion_modules.0.transformer_blocks.0.pos_embed.pe
down_blocks.1.motion_modules.1.transformer_blocks.0.pos_embed.pe
down_blocks.2.motion_modules.0.transformer_blocks.0.pos_embed.pe
down_blocks.2.motion_modules.1.transformer_blocks.0.pos_embed.pe
down_blocks.3.motion_modules.0.transformer_blocks.0.pos_embed.pe
down_blocks.3.motion_modules.1.transformer_blocks.0.pos_embed.pe
up_blocks.0.motion_modules.0.transformer_blocks.0.pos_embed.pe
up_blocks.0.motion_modules.1.transformer_blocks.0.pos_embed.pe
up_blocks.0.motion_modules.2.transformer_blocks.0.pos_embed.pe
up_blocks.1.motion_modules.0.transformer_blocks.0.pos_embed.pe
up_blocks.1.motion_modules.1.transformer_blocks.0.pos_embed.pe
up_blocks.1.motion_modules.2.transformer_blocks.0.pos_embed.pe
up_blocks.2.motion_modules.0.transformer_blocks.0.pos_embed.pe
up_blocks.2.motion_modules.1.transforme

In [2]:
print(model['down_blocks.0.motion_modules.0.transformer_blocks.0.pos_embed.pe'])

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
           0.0000e+00,  1.0000e+00],
         [ 8.4131e-01,  5.4053e-01,  8.1006e-01,  ...,  1.0000e+00,
           1.0592e-04,  1.0000e+00],
         [ 9.0918e-01, -4.1626e-01,  9.5020e-01,  ...,  1.0000e+00,
           2.1183e-04,  1.0000e+00],
         ...,
         [-6.6357e-01, -7.4805e-01,  7.8125e-01,  ...,  1.0000e+00,
           3.0727e-03,  1.0000e+00],
         [-9.8779e-01,  1.5430e-01, -4.7485e-02,  ...,  1.0000e+00,
           3.1776e-03,  1.0000e+00],
         [-4.0405e-01,  9.1455e-01, -8.3691e-01,  ...,  1.0000e+00,
           3.2845e-03,  1.0000e+00]]])


In [3]:

model2 = torch.load('checkpoints/sd15_latent_new_lr_1e-5_4a100-with-motion-no-update-1004/checkpoint-200000/pytorch_model.bin',map_location='cpu')
print(model2['down_blocks.0.motion_modules.0.transformer_blocks.0.pos_embed.pe'])

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
           0.0000e+00,  1.0000e+00],
         [ 8.4131e-01,  5.4053e-01,  8.1006e-01,  ...,  1.0000e+00,
           1.0592e-04,  1.0000e+00],
         [ 9.0918e-01, -4.1626e-01,  9.5020e-01,  ...,  1.0000e+00,
           2.1183e-04,  1.0000e+00],
         ...,
         [-6.6357e-01, -7.4805e-01,  7.8125e-01,  ...,  1.0000e+00,
           3.0727e-03,  1.0000e+00],
         [-9.8779e-01,  1.5430e-01, -4.7485e-02,  ...,  1.0000e+00,
           3.1776e-03,  1.0000e+00],
         [-4.0405e-01,  9.1455e-01, -8.3691e-01,  ...,  1.0000e+00,
           3.2845e-03,  1.0000e+00]]])


In [4]:
model['down_blocks.0.motion_modules.0.transformer_blocks.0.pos_embed.pe']==model2['down_blocks.0.motion_modules.0.transformer_blocks.0.pos_embed.pe']


tensor([[[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]])

In [1]:
import torch
from safetensors.torch import load_file, save_file

model = load_file('checkpoints/train_sdxl_lora/checkpoint-30000/pytorch_lora_weights.safetensors')

In [2]:
for key in model.keys():
    print(key)

unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_k.lora.down.weight
unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_k.lora.up.weight
unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_out.0.lora.down.weight
unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_out.0.lora.up.weight
unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_q.lora.down.weight
unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_q.lora.up.weight
unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_v.lora.down.weight
unet.down_blocks.0.motion_modules.0.transformer_blocks.0.attn1.to_v.lora.up.weight
unet.down_blocks.0.motion_modules.1.transformer_blocks.0.attn1.to_k.lora.down.weight
unet.down_blocks.0.motion_modules.1.transformer_blocks.0.attn1.to_k.lora.up.weight
unet.down_blocks.0.motion_modules.1.transformer_blocks.0.attn1.to_out.0.lora.down.weight
unet.down_blocks.0.motion_modules.1.transformer_blocks.0.attn1.

In [1]:
import json
with open("datasets/sh_CeleV-Text/processed_sd15.json", 'r') as file:
    all_data = json.load(file)

In [2]:
len(all_data)

67006